# Generated by Django 3.0.7 on 2020-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
