# Generated by Django 3.0.7 on 2020-08-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_happiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='happiness',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
