# Generated by Django 3.0.7 on 2020-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_happiness_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('sedentary', models.IntegerField()),
                ('moderately_active', models.IntegerField()),
                ('active', models.IntegerField()),
            ],
        ),
    ]
