# Generated by Django 3.0.7 on 2020-08-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200824_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField()),
                ('activeLevel', models.CharField(choices=[('s', 'sedentary'), ('m', 'Moderately Active'), ('a', 'Active')], default='s', max_length=1)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
            ],
        ),
    ]
