# Generated by Django 3.0.7 on 2020-09-10 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('carbs', models.CharField(max_length=64)),
                ('fat', models.CharField(max_length=64)),
                ('food_id', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
                ('protein', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
