# Generated by Django 3.0.7 on 2020-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
