# Generated by Django 3.0.7 on 2020-09-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_favorite_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='like',
        ),
    ]
