# Generated by Django 3.0.7 on 2020-09-22 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_favorite_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
